---
title: "Final Project Part 1: Wrangling"
author: "Lex Clay"
date: "2026-04-20"
output: html_document
---

```{r setup,echo=FALSE}
library(readxl)
library(lubridate)
library(here)
library(tidyverse)
library(janitor)
library(mapview)
library(tidycensus)
library(sf)
library(readr)

#census_api_key("API WAS HERE", install = TRUE)

```

DATA WRANGLING STEP 1: Joining reactor coordinate and water source data 

```{r Importing Nuclear Sites Data}

#I am working with two datasets to get the lat and long of each site. In some instances, like at McGuire, there are multiple units at one site. In this project I will be working with distance from sites, not individual units. 

gen_raw <- read.csv(here("Final_Project/Data/nuclear_units.csv"),skip=1,check.names = FALSE)

gen <- gen_raw %>% clean_names()

gen$nameplate_capacity_mw <- as.numeric(gsub(",", "", gen$nameplate_capacity_mw))

#filtering to nuclear units 

nuc_units <- gen %>%  
  filter(technology=="Nuclear") %>% 
select(utility_id, utility_name, plant_code, plant_name, state, county, nameplate_capacity_mw, operating_year)
  
#aggregating units to sites by plant codes. 

nuc_sites <- nuc_units %>%  
  group_by(plant_code) %>% 
  summarise(
    n_units = n(), 
    total_nameplate_mw = sum(nameplate_capacity_mw, na.rm = TRUE),
    first_online_year = min(operating_year, na.rm = TRUE),
    last_online_year =max(operating_year, na.rm = TRUE),
    .groups = "drop"
    )

```

```{r Import Plant and Water Source Data }

plant.raw <- read.csv(here("Final_Project/Data/plant_watersource.csv"), skip = 1, check.names = FALSE)

plant <- plant.raw %>% clean_names()
```


```{r Join Data Sets}

nuclear_join <- plant %>%  
  inner_join(nuc_sites, by="plant_code") %>%  
  select(plant_code, plant_name, utility_name, state, county,
         latitude, longitude, water_source = name_of_water_source,
         n_units, total_nameplate_mw,
         first_online_year, last_online_year)

write.csv(nuclear_join, 
          here("Final_Project/Data/Processed/nuclear_join.csv"), 
          row.names = FALSE)
```

DATA WRANGLING STEP 2: Pulling Household Income with Tidycensus 

```{r}
conus_states <- state.abb[!state.abb %in% c("AK","HI")]

acs_tracts <- get_acs(
  geography = "tract", 
  variables = "B19013_001", 
  year =2024, 
  survey = "acs5", 
  state = conus_states,
  geometry = TRUE,            # returns sf object with tract polygons
  output = "wide"
) %>%
  rename(median_hh_income = B19013_001E,
         median_hh_income_moe = B19013_001M) %>%
  st_transform(5070)  

saveRDS(acs_tracts, here("Final_Project/Data/Processed/acs_tracts.rds"))

```

```{r}

acs_tracts <- read_rds(here("Final_Project/Data/Processed/acs_tracts.rds"))
  
```


```{r}

nuclear_sf <- nuclear_join %>%
  st_as_sf(coords = c("longitude", "latitude"), crs=4326, remove = FALSE)

nuclear_albers <- nuclear_sf %>% st_transform(5070)

saveRDS(nuclear_sf, 
        here("Final_Project/Data/Processed/nuclear_sf.rds"))

mapview(nuclear_sf)
```

```{r Calculate Distance from Tract to Plant}

tract_centroids <- st_centroid(acs_tracts)

nearest_idx <- st_nearest_feature(tract_centroids, nuclear_albers)

tracts_with_dist <- acs_tracts %>%
  mutate(
    nearest_plant_code = nuclear_albers$plant_code[nearest_idx],
    nearest_plant_name = nuclear_albers$plant_name[nearest_idx],
    dist_to_reactor_m = as.numeric(
      st_distance(tract_centroids, nuclear_albers[nearest_idx, ], by_element = TRUE)
    ),
    dist_to_reactor_mi = dist_to_reactor_m / 1609.34
  )

#dropping NA for track distance and mm hh income 

tracts_clean <- tracts_with_dist %>%
  filter(!is.na(dist_to_reactor_m),
         !is.na(median_hh_income))

saveRDS(tracts_clean, here("Final_Project/Data/Processed/tracts_clean.rds"))
```

